# Generated by Django 2.2.6 on 2019-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название формы')),
                ('text', models.TextField(max_length=5000, verbose_name='Предзаполненный список')),
                ('image', models.ImageField(upload_to='covers', verbose_name='Фото продукта')),
            ],
            options={
                'verbose_name': 'Форма продукта',
                'verbose_name_plural': 'Формы продуктов',
            },
        ),
    ]
