# Generated by Django 2.2.6 on 2019-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправления'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='full_text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receive_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Краткое описание'),
        ),
    ]
