# Generated by Django 2.2.6 on 2019-10-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_invoices', '0002_auto_20191003_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Фото продукта'),
        ),
    ]
